# Generated by Django 6.0.1 on 2026-06-08 17:45

from django.db import migrations, models

def update_currency_to_eur(apps, schema_editor):
    PaymentTransaction = apps.get_model('payments', 'PaymentTransaction')
    PaymentTransaction.objects.filter(currency='USD').update(currency='EUR')


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransaction_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.RunPython(update_currency_to_eur),
    ]
