# Generated by Django 6.0.1 on 2026-04-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='প্রশ্ন')),
                ('answer', models.TextField(verbose_name='উত্তর')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
