# Generated by Django 6.0.1 on 2026-04-17 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ক্যাটাগরি নাম')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='স্লাগ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='dashboard.faqcategory', verbose_name='ক্যাটাগরি'),
        ),
    ]
