# Generated by Django 6.0.1 on 2026-04-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_contactmessage_successstory_instructorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. Frontend Developer', max_length=100)),
                ('location', models.CharField(help_text='e.g. Norway', max_length=100)),
                ('photo', models.ImageField(upload_to='community_stories/')),
                ('story_url', models.URLField(blank=True, null=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Community Stories',
                'ordering': ['order_index', '-created_at'],
            },
        ),
    ]
