# Generated by Django 6.0.1 on 2026-04-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_communitystory'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='designation',
            field=models.CharField(blank=True, help_text='e.g. Senior French Instructor', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='total_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
