# Generated by Django 6.0.1 on 2026-04-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_instructorprofile_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitystory',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography', null=True),
        ),
        migrations.AddField(
            model_name='communitystory',
            name='full_story',
            field=models.TextField(blank=True, help_text='Detailed story content', null=True),
        ),
        migrations.AddField(
            model_name='communitystory',
            name='quote',
            field=models.TextField(blank=True, help_text='Featured quote', null=True),
        ),
        migrations.AlterField(
            model_name='communitystory',
            name='story_url',
            field=models.URLField(blank=True, help_text='Optional external link', null=True),
        ),
    ]
