# Generated by Django 5.2.5 on 2025-12-18 06:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField(help_text='Total exam duration in minutes')),
                ('total_marks', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exams', to='courses.level')),
            ],
            options={
                'verbose_name': 'Mock Exam',
                'verbose_name_plural': 'Mock Exams',
                'db_table': 'mock_exams',
            },
        ),
        migrations.CreateModel(
            name='MockExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SUBMITTED', 'Submitted')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('listening_score', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('reading_score', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('writing_score', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('speaking_score', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.mockexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mock Exam Attempt',
                'verbose_name_plural': 'Mock Exam Attempts',
                'db_table': 'mock_exam_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MockExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField(help_text='Section duration in minutes')),
                ('marks', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('order_index', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sections', to='courses.category')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.mockexam')),
            ],
            options={
                'verbose_name': 'Mock Exam Section',
                'verbose_name_plural': 'Mock Exam Sections',
                'db_table': 'mock_exam_sections',
                'ordering': ['exam', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ_SINGLE', 'Multiple Choice (Single Answer)'), ('MCQ_MULTIPLE', 'Multiple Choice (Multiple Answers)'), ('TRUE_FALSE', 'True / False'), ('FILL_BLANK', 'Fill in the Blank'), ('MATCHING', 'Matching'), ('YES_NO_NOT_MENTIONED', 'Yes / No / Not Mentioned'), ('INFORMATION_EXTRACTION', 'Information Extraction'), ('EMAIL_WRITING', 'Email Writing'), ('SHORT_PARAGRAPH', 'Short Paragraph'), ('OPINION_TEXT', 'Opinion-based Text'), ('ROLE_PLAY', 'Role-play Simulation'), ('IMAGE_DESCRIPTION', 'Image-based Description'), ('TOPIC_MONOLOGUE', 'Topic Monologue')], max_length=50)),
                ('text', models.TextField(help_text='Question text or prompt')),
                ('instruction', models.TextField(blank=True, help_text="Instructions for answering (e.g., 'Choose the best answer', 'Fill in the blanks')")),
                ('marks', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_url', models.URLField(blank=True, help_text='Audio file URL for listening questions', null=True)),
                ('passage', models.TextField(blank=True, help_text='Reading passage or text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.level')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.videolesson')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
                'ordering': ['video', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order_index', models.IntegerField(default=0)),
                ('match_key', models.CharField(blank=True, help_text='Key for matching pairs', max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'db_table': 'options',
                'ordering': ['question', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, help_text='Text answer for writing/speaking questions')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('AUTO_GRADED', 'Auto Graded')], default='PENDING', max_length=20)),
                ('feedback', models.TextField(blank=True, help_text='Instructor feedback')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.question')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('selected_options', models.ManyToManyField(blank=True, help_text='Selected options for MCQ questions', to='exams.option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MockExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.mockexamsection')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exam_questions', to='exams.question')),
            ],
            options={
                'verbose_name': 'Mock Exam Question',
                'verbose_name_plural': 'Mock Exam Questions',
                'db_table': 'mock_exam_questions',
                'ordering': ['section', 'order_index'],
                'unique_together': {('section', 'question')},
            },
        ),
    ]
