# Generated by Django 5.2.9 on 2026-01-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Audio file for listening questions', null=True, upload_to='question_audio/'),
        ),
    ]
