# Generated by Django 5.2.9 on 2026-01-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='file',
            field=models.FileField(blank=True, help_text='File for option', null=True, upload_to='option_file/'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
