# Generated by Django 6.0.1 on 2026-01-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_videolesson_video_file_alter_videolesson_video_url'),
        ('exams', '0003_option_file_alter_option_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Exercise label (e.g., 'EXERCICE 3')", max_length=100)),
                ('title', models.TextField(blank=True, help_text="Exercise instructions (e.g., 'Lisez les questions. Écoutez le document puis répondez.')")),
                ('context_text', models.TextField(blank=True, help_text="Scenario or context text (e.g., 'Vous travaillez en France...')")),
                ('total_points', models.DecimalField(blank=True, decimal_places=2, help_text='Total points for this exercise', max_digits=5, null=True)),
                ('order_index', models.IntegerField(default=0, help_text='Order of this exercise in the video')),
                ('audio_url', models.URLField(blank=True, help_text='Audio file URL for listening context', null=True)),
                ('audio_file', models.FileField(blank=True, help_text='Audio file for listening context', null=True, upload_to='exercise_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_contexts', to='courses.videolesson')),
            ],
            options={
                'verbose_name': 'Exercise Context',
                'verbose_name_plural': 'Exercise Contexts',
                'db_table': 'exercise_contexts',
                'ordering': ['video', 'order_index'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='exercise_context',
            field=models.ForeignKey(blank=True, help_text='Shared context for this question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exams.exercisecontext'),
        ),
    ]
