# Generated by Django 6.0.1 on 2026-01-11 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exercisecontext_question_exercise_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExamPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Advanced')], db_index=True, max_length=2)),
                ('name', models.CharField(help_text="Package name (e.g., 'A1 Complete Mock Exam Package')", max_length=200)),
                ('description', models.TextField(help_text="Detailed description of what's included")),
                ('price', models.DecimalField(decimal_places=2, help_text='Package price', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('exam_count', models.IntegerField(help_text='Number of exams in this package')),
                ('features', models.JSONField(default=list, help_text='List of features as JSON array')),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular/recommended')),
                ('display_order', models.IntegerField(default=0, help_text='Order to display on pricing page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mock Exam Package',
                'verbose_name_plural': 'Mock Exam Packages',
                'db_table': 'mock_exam_packages',
                'ordering': ['display_order', 'level'],
            },
        ),
        migrations.AddField(
            model_name='mockexam',
            name='is_free',
            field=models.BooleanField(default=False, help_text='If true, exam is accessible without purchase'),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Package this exam belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='exams.mockexampackage'),
        ),
        migrations.CreateModel(
            name='MockExamPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the purchase')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='exams.mockexampackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exam_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mock Exam Purchase',
                'verbose_name_plural': 'Mock Exam Purchases',
                'db_table': 'mock_exam_purchases',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='MockExamAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='exams.mockexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exam_access', to=settings.AUTH_USER_MODEL)),
                ('granted_via_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access', to='exams.mockexampurchase')),
            ],
            options={
                'verbose_name': 'Mock Exam Access',
                'verbose_name_plural': 'Mock Exam Access',
                'db_table': 'mock_exam_access',
                'ordering': ['-granted_at'],
                'unique_together': {('user', 'exam')},
            },
        ),
    ]
