# Generated by Django 6.0.1 on 2026-04-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_mockexampackage_mockexam_is_free_mockexam_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Feature name (e.g., 'PDF Explanations')", max_length=200)),
                ('icon', models.CharField(default='fas fa-check-circle', help_text='FontAwesome icon class', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Package Feature',
                'verbose_name_plural': 'Package Features',
                'db_table': 'package_features',
            },
        ),
        migrations.RemoveField(
            model_name='mockexampackage',
            name='features',
        ),
        migrations.AddField(
            model_name='mockexampackage',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='List of features', related_name='packages', to='exams.packagefeature'),
        ),
    ]
