# Generated by Django 6.0.1 on 2026-06-08 17:45

from django.db import migrations, models

def update_currency_to_eur(apps, schema_editor):
    MockExamPackage = apps.get_model('exams', 'MockExamPackage')
    MockExamPurchase = apps.get_model('exams', 'MockExamPurchase')
    MockExamPackage.objects.filter(currency='USD').update(currency='EUR')
    MockExamPurchase.objects.filter(currency='USD').update(currency='EUR')


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_packagefeature_remove_mockexampackage_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockexampackage',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='mockexampurchase',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.RunPython(update_currency_to_eur),
    ]
