# Generated by Django 6.0.6 on 2026-06-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_mockexampackage_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockexamsection',
            name='category',
        ),
    ]
