# Generated by Django 6.0.6 on 2026-06-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_videolesson_category_alter_chapter_options_and_more'),
        ('exams', '0008_remove_mockexamsection_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockexampackage',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_exam_packages', to='courses.levelcode'),
        ),
    ]
