# Generated by Django 6.0.6 on 2026-06-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_mockexampackage_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockexam',
            name='included_with_enrollment',
            field=models.BooleanField(default=False, help_text='If true, course-enrolled students get free access'),
        ),
    ]
