# Generated by Django 5.2.5 on 2025-12-18 06:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LISTENING', "Compréhension de l'oral (Listening)"), ('READING', 'Compréhension des écrits (Reading)'), ('WRITING', 'Production écrite (Writing)'), ('SPEAKING', 'Production orale (Speaking)')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order_index', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate')], max_length=10, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'db_table': 'levels',
                'ordering': ['order_index', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_full_access', models.BooleanField(default=False, help_text='If True, provides access to all levels')),
                ('duration_months', models.IntegerField(blank=True, help_text='Access duration in months (null = lifetime)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.level')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objectives', models.TextField(help_text='Learning objectives for this chapter')),
                ('grammar_focus', models.TextField(blank=True, help_text='Grammar topics covered')),
                ('vocabulary_list', models.TextField(blank=True, help_text='Key vocabulary')),
                ('cultural_notes', models.TextField(blank=True, help_text='Cultural context')),
                ('exam_relevance', models.TextField(blank=True, help_text='How this relates to DELF/DALF')),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.level')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'db_table': 'chapters',
                'ordering': ['level', 'order_index'],
                'unique_together': {('level', 'order_index')},
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('learning_goals', models.TextField(help_text='What students will learn')),
                ('grammar_explanation', models.TextField(blank=True)),
                ('vocabulary_explanation', models.TextField(blank=True)),
                ('example_dialogues', models.TextField(blank=True)),
                ('video_url', models.URLField(help_text='URL to video file (YouTube, Vimeo, or direct link)')),
                ('duration', models.IntegerField(help_text='Duration in seconds', validators=[django.core.validators.MinValueValidator(1)])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='courses.category')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.chapter')),
            ],
            options={
                'verbose_name': 'Video Lesson',
                'verbose_name_plural': 'Video Lessons',
                'db_table': 'video_lessons',
                'ordering': ['chapter', 'order_index'],
            },
        ),
    ]
