# Generated by Django 5.2.5 on 2026-01-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file directly (alternative to Video URL)', null=True, upload_to='course_videos/'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to video file (YouTube, Vimeo, or direct link)', null=True),
        ),
    ]
