# Generated by Django 6.0.1 on 2026-04-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_videolesson_video_file_alter_videolesson_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='lesson_resources/')),
                ('resource_type', models.CharField(choices=[('PDF', 'PDF Document'), ('IMAGE', 'Image'), ('DOC', 'Document'), ('OTHER', 'Other')], default='PDF', max_length=10)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.videolesson')),
            ],
            options={
                'verbose_name': 'Lesson Resource',
                'verbose_name_plural': 'Lesson Resources',
                'db_table': 'lesson_resources',
                'ordering': ['order_index'],
            },
        ),
    ]
