# Generated by Django 6.0.1 on 2026-06-06 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_level_currency_level_discounted_price_level_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Word or phrase in French', max_length=200)),
                ('ipa_pronunciation', models.CharField(blank=True, help_text='IPA phonetic transcription (optional)', max_length=200)),
                ('meaning', models.TextField(help_text='Meaning of the word in text (e.g. English or Bengali)')),
                ('audio_file', models.FileField(blank=True, help_text='Audio file for pronunciation', null=True, upload_to='word_pronunciations/')),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_meanings', to='courses.videolesson')),
            ],
            options={
                'verbose_name': 'Word Meaning',
                'verbose_name_plural': 'Word Meanings',
                'db_table': 'word_meanings',
                'ordering': ['order_index', 'word'],
            },
        ),
    ]
