# Generated by Django 6.0.1 on 2026-06-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_wordmeaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
