# Generated by Django 6.0.1 on 2026-06-08 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_level_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. A1, A2, B1, B2', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional description/name of the level code', max_length=100)),
            ],
            options={
                'verbose_name': 'Level Code',
                'verbose_name_plural': 'Level Codes',
                'db_table': 'level_codes',
            },
        ),
        migrations.AddField(
            model_name='level',
            name='level_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='courses.levelcode'),
        ),
    ]
