# Generated by Django 6.0.1 on 2026-06-08 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_levelcode_level_level_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['order_index', 'level_code__code'], 'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
        migrations.RemoveField(
            model_name='level',
            name='code',
        ),
        migrations.AlterField(
            model_name='level',
            name='level_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='courses.levelcode'),
        ),
    ]
