# Generated by Django 6.0.1 on 2026-06-08 17:45

from django.db import migrations, models

def update_currency_to_eur(apps, schema_editor):
    Level = apps.get_model('courses', 'Level')
    Course = apps.get_model('courses', 'Course')
    Level.objects.filter(currency='USD').update(currency='EUR')
    Course.objects.filter(currency='USD').update(currency='EUR')


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_level_options_remove_level_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='level',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.RunPython(update_currency_to_eur),
    ]
