# Generated by Django 6.0.6 on 2026-06-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_currency_alter_level_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='chapters',
            field=models.ManyToManyField(blank=True, help_text='Specific chapters included in this course (ignored if is_full_access is True)', related_name='courses', to='courses.chapter'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_full_access',
            field=models.BooleanField(default=False, help_text='If True, gives access to all chapters under the level'),
        ),
    ]
