# Generated by Django 6.0.6 on 2026-06-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_chapters_alter_course_is_full_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text='One outcome per line. Shown as bullet points on the course page.'),
        ),
    ]
