# Generated by Django 6.0.6 on 2026-06-25 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_learning_outcomes'),
        ('exams', '0008_remove_mockexamsection_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolesson',
            name='category',
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['course', 'order_index'], 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course', 'order_index')},
        ),
        migrations.RemoveField(
            model_name='course',
            name='chapters',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='level',
        ),
    ]
